namespace: apps
replicaCount: 1

image:
  repository: ghcr.io/p-o-d/deploy-test-app
  tag: 59bf68c5d3bafc7e297479b09eac778300a3d01b
  pullPolicy: Always
  pullSecrets: []

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: deploy.local.lan
      path: /
  tls: []                             

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
