namespace: apps
replicaCount: 1

image:
  repository: ghcr.io/p-o-d/deploy-test-app
  tag: 0996fe0449ad6f305e5278f212f43228274d1374
  pullPolicy: Always
  pullSecrets: []

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: deploy.local.lan
      path: /
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
