{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deploy-test-app
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: deploy-test-app
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: deploy-test-app
                port:
                  number: {{ $.Values.service.port }}
  {{- end }}
{{- end }}
